# Generated by Django 2.1.7 on 2019-02-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('imagem', models.FileField(default='imovel/default.jpg', upload_to='imovel/')),
                ('perfis', models.ManyToManyField(related_name='imoveis', to='usuario.Perfil')),
            ],
        ),
    ]
